### ISSUE TITLE
Andruzzzkah installer.

### ISSUE THREAD

**Issue by ghostiekitty** [200Tigersbloxed/BSMulti-Installer#3]
Seems like the installer is giving people a customavatars dll with 0kb...might wanna look into that...

**Comment by 200Tigersbloxed** [comment]
Found the issue. Github returned a 404 on the link for whatever reason, so I uploaded it elsewhere, and then changed the 301 redirect link to go there from now on. Did not even notice this, thanks for pointing it out. Feel free to re-open this issue if this occurs again with any other file.
