### ISSUE TITLE
Multiplayer not installed after 5 tries

### ISSUE THREAD

**Issue by Fatalution** [200Tigersbloxed/BSMulti-Installer#5]
It just doesn't get installed. 

What I have tried:
1. Installing normally 
2. Launching the installer with admin privileges
3. Installing manually (!)
4. Reinstalling BSMultiplayer to the C driver and trying 1-3 again

None of those steps helped. Installing the multiplayer with the installer does download files, but nothing changes in Beat Saber. Putting files manually to Beat Saber folder changes _nothing_.

**Comment by 200Tigersbloxed** [comment]
Assuming you've already fixed this judging from the message you sent in the discord.
<img width="810" alt="Screen Shot 2020-07-17 at 10 12 57 AM" src="https://user-images.githubusercontent.com/45884377/87795620-53dc3e80-c816-11ea-8564-52d8c8808c1b.png">
